# In-Class Assignment 4

Consider the `framingham.csv` data file. The dataset is publicly available on the Kaggle website, and it is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. The classification goal is to predict whether the patient has 10-year risk of future coronary heart disease (CHD). The dataset provides the patients' information. It includes over 4,000 records and 15 attributes. Each attribute is a potential risk factor. There are demographic, behavioral and medical risk factors.

- **Demographic**
  - Sex: male or female (Nominal)
  - Age: Age of the patient (Continuous - although recorded ages have been truncated to whole numbers, the concept of age is continuous)
- **Behavioral**
  - Current Smoker: whether or not the patient is a current smoker (Nominal)
  - Cigs Per Day: the number of cigarettes that the person smoked on average in one day (can be considered continuous)
- **Medical (history)**
  - BP Meds: whether or not the patient was on blood pressure medication (Nominal)
  - Prevalent Stroke: whether or not the patient had previously had a stroke (Nominal)
  - Prevalent Hyp: whether or not the patient was hypertensive (Nominal)
  - Diabetes: whether or not the patient had diabetes (Nominal)
- **Medical (current)**
  - Tot Chol: total cholesterol level (Continuous)
  - Sys BP: systolic blood pressure (Continuous)
  - Dia BP: diastolic blood pressure (Continuous)
  - BMI: Body Mass Index (Continuous)
  - Heart Rate: heart rate (Continuous)
  - Glucose: glucose level (Continuous)
- **Predict variable (desired target)**
  - 10 year risk of coronary heart disease CHD (binary: "1" means "Yes", "0" means "No")

In **Python**, answer the following:

## 1. (3 points)
Using the pandas library, read the csv data file and create a data-frame called `heart`.

In [3]:
import pandas as pd 

heart = pd.read_csv("framingham.csv")
heart.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [4]:
heart.shape

(4238, 16)

## 2. (3 points)
Remove observations with missing values.

In [5]:
heart = heart.dropna()
heart.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [6]:
heart.shape

(3656, 16)

## 3. (4 points)
Using `age`, `currentSmoker`, `totChol`, `BMI`, and `heartRate` as the predictor variables, and `TenYearCHD` as the target variable, split the data into two data-frames: train (80%) and test (20%).

In [7]:
# Defining the input and target variables
X = heart[["age", "currentSmoker", "totChol", "BMI", "heartRate"]]
y = heart["TenYearCHD"]

# Splitting the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 4. (5 points)
Using the train data-frame, build a logistic regression model in which: `age`, `currentSmoker`, `totChol`, `BMI`, and `heartRate` are the predictor variables, and `TenYearCHD` is the target variable.

In [8]:
from sklearn.linear_model import LogisticRegression

# Building and training the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

## 5. (5 points)
Using the model from part 4, predict the likelihood of risk of coronary disease of the patients in the test data-frame. Using 25% as cutoff value, report the confusion matrix and the accuracy.

In [11]:
# Predicting on the test set
y_pred = model.predict_proba(X_test)[:, 1]
y_pred

array([0.06253485, 0.01910806, 0.41002059, 0.08597277, 0.15770722,
       0.18133598, 0.03971542, 0.16749722, 0.15988221, 0.47172007,
       0.1427508 , 0.03348776, 0.31292258, 0.28845941, 0.33102345,
       0.3433191 , 0.08992236, 0.09050726, 0.07519171, 0.03745704,
       0.03875408, 0.18646246, 0.10130562, 0.28385639, 0.26177397,
       0.0862168 , 0.22820035, 0.1630918 , 0.19602771, 0.09689252,
       0.14403281, 0.09619444, 0.09999984, 0.08718253, 0.05442263,
       0.24416414, 0.10263954, 0.29759632, 0.08971474, 0.03756519,
       0.22256632, 0.03054483, 0.14359751, 0.06224248, 0.03795978,
       0.03596424, 0.11388699, 0.28014584, 0.17624929, 0.06516498,
       0.27391362, 0.04778704, 0.12069558, 0.21678923, 0.14593038,
       0.07941982, 0.36176663, 0.10406811, 0.35555098, 0.07108453,
       0.19694578, 0.14384029, 0.19056365, 0.04248183, 0.06307951,
       0.11318622, 0.11312752, 0.05077852, 0.0381639 , 0.24300735,
       0.07729191, 0.16487541, 0.23041308, 0.03818488, 0.11203835,
       0.09873131, 0.06089362, 0.10758698, 0.05694447, 0.07738589,
       0.27817842, 0.04291683, 0.07737741, 0.04619699, 0.08667765,
       0.28375133, 0.06187747, 0.17548193, 0.1527737 , 0.14379109,
       0.3048357 , 0.24321362, 0.13036976, 0.06005013, 0.05064896,
       0.10631728, 0.28159841, 0.06824976, 0.11470365, 0.18560361,
       0.23813481, 0.05946951, 0.11788192, 0.10099128, 0.06632708,
       0.07612174, 0.06126585, 0.04885945, 0.07836162, 0.18179444,
       0.08718921, 0.1360314 , 0.32428278, 0.05055306, 0.3388513 ,
       0.11854601, 0.16688893, 0.02924874, 0.05926556, 0.1310941 ,
       0.08125232, 0.10593346, 0.12204912, 0.0655275 , 0.06342961,
       0.32145998, 0.141849  , 0.10850371, 0.05909492, 0.19820225,
       0.25715244, 0.04548688, 0.08342359, 0.11718568, 0.04574083,
       0.18855132, 0.17749771, 0.30208932, 0.44629372, 0.12852755,
       0.21117961, 0.0434858 , 0.05463458, 0.05116479, 0.28508838,
       0.06597208, 0.37627685, 0.21400902, 0.14858973, 0.10383313,
       0.13417595, 0.39605896, 0.13326762, 0.33154178, 0.14352588,
       0.20391012, 0.07478221, 0.12419044, 0.19861211, 0.20442805,
       0.07509973, 0.05857141, 0.08504959, 0.10237437, 0.25471484,
       0.02509668, 0.31942207, 0.11498506, 0.07560321, 0.31698185,
       0.07774074, 0.19960352, 0.02375009, 0.2206623 , 0.10277951,
       0.29369551, 0.07041556, 0.29270342, 0.07094883, 0.03420507,
       0.12546467, 0.19720995, 0.28240418, 0.0427343 , 0.1160925 ,
       0.30634545, 0.05372429, 0.15026329, 0.08059231, 0.1371193 ,
       0.17637434, 0.08131582, 0.04388121, 0.07040967, 0.15362018,
       0.03165856, 0.06462626, 0.04125599, 0.14556349, 0.23413801,
       0.18662774, 0.11101621, 0.36042736, 0.05080548, 0.14260084,
       0.17541597, 0.17788451, 0.10218622, 0.13051471, 0.06864306,
       0.05990669, 0.27007042, 0.0962937 , 0.10671299, 0.17790949,
       0.19866907, 0.05717695, 0.2761204 , 0.18912763, 0.13100333,
       0.14406016, 0.20696292, 0.08309052, 0.21536077, 0.03565872,
       0.07670626, 0.0289543 , 0.18867364, 0.40123812, 0.09305127,
       0.04725755, 0.09405068, 0.30251543, 0.08143151, 0.30054726,
       0.09036891, 0.26285162, 0.31776881, 0.04776209, 0.31912281,
       0.08374549, 0.0668427 , 0.09916317, 0.02566014, 0.09572153,
       0.21465028, 0.07128735, 0.24873489, 0.06210257, 0.06075576,
       0.16102096, 0.14856176, 0.05825075, 0.15992038, 0.10371075,
       0.09327688, 0.24988715, 0.2560143 , 0.08386491, 0.18972002,
       0.06832845, 0.51472173, 0.2461381 , 0.33205493, 0.0656727 ,
       0.13842965, 0.08045228, 0.11236622, 0.05164616, 0.33904469,
       0.04078989, 0.22513954, 0.09644487, 0.04964814, 0.15439235,
       0.23676153, 0.18045968, 0.18929337, 0.34421124, 0.12886915,
       0.21985828, 0.11214282, 0.20761385, 0.09590249, 0.06257573,
       0.20068011, 0.1763031 , 0.09671364, 0.06642036, 0.09847721,
       0.08271593, 0.27628372, 0.07498952, 0.07503862, 0.07619319,
       0.18173666, 0.12518465, 0.2674852 , 0.10993547, 0.17920922,
       0.1008446 , 0.18857379, 0.18840547, 0.14959725, 0.09729816,
       0.0492193 , 0.02562539, 0.21776396, 0.10841548, 0.30297855,
       0.10174906, 0.12805497, 0.18541229, 0.13110342, 0.10130882,
       0.37735491, 0.15483467, 0.03669471, 0.10786027, 0.17653926,
       0.12902499, 0.06072396, 0.04986401, 0.07944169, 0.27254853,
       0.04235262, 0.04185477, 0.32374651, 0.18267471, 0.11606255,
       0.23228082, 0.11519802, 0.31472439, 0.25122394, 0.1771417 ,
       0.18687236, 0.07249035, 0.0278401 , 0.15225512, 0.14579756,
       0.03933837, 0.48621928, 0.13128779, 0.27631911, 0.1840241 ,
       0.2964327 , 0.06468213, 0.08708962, 0.13566691, 0.11034981,
       0.16097593, 0.06088894, 0.03003496, 0.14589726, 0.110222  ,
       0.25021245, 0.11695927, 0.04113083, 0.04532437, 0.08075178,
       0.12246343, 0.05303739, 0.05434876, 0.08575569, 0.14687626,
       0.23762536, 0.14928798, 0.08648821, 0.23556893, 0.31649955,
       0.02989371, 0.15946963, 0.27237602, 0.27007891, 0.13639601,
       0.24232785, 0.19750456, 0.26163815, 0.28041086, 0.07780043,
       0.13854912, 0.0536113 , 0.18829513, 0.27301997, 0.17666458,
       0.23189021, 0.18047563, 0.33824679, 0.04670063, 0.0338468 ,
       0.1041119 , 0.100597  , 0.07168936, 0.16035768, 0.44042867,
       0.14405315, 0.37612411, 0.09412558, 0.10821537, 0.06540237,
       0.18149185, 0.04961767, 0.21599946, 0.18687954, 0.2350674 ,
       0.06209767, 0.033216  , 0.38628295, 0.15945148, 0.25024795,
       0.13717955, 0.06546745, 0.0459443 , 0.38109607, 0.21532641,
       0.35117851, 0.12199126, 0.07001498, 0.11046731, 0.2173859 ,
       0.21274767, 0.18931452, 0.06306182, 0.05441812, 0.06717406,
       0.05831044, 0.25409242, 0.31403801, 0.04539657, 0.33535769,
       0.04727957, 0.08194732, 0.11901416, 0.14048108, 0.04653598,
       0.21560433, 0.05279917, 0.43993225, 0.16270922, 0.33153713,
       0.14871123, 0.07507316, 0.21109786, 0.08763235, 0.09727182,
       0.14237545, 0.08599928, 0.03258702, 0.22864603, 0.06629691,
       0.12351138, 0.18335753, 0.20573965, 0.3142434 , 0.09224234,
       0.05153228, 0.25033402, 0.14543057, 0.04245252, 0.23831236,
       0.11801398, 0.143734  , 0.06139741, 0.15149493, 0.2350795 ,
       0.1008714 , 0.18116682, 0.0617633 , 0.13586803, 0.10761814,
       0.1080932 , 0.05102289, 0.17720489, 0.10988412, 0.03584553,
       0.25590461, 0.09301642, 0.04524535, 0.10913354, 0.24208699,
       0.25402199, 0.31219272, 0.0638452 , 0.09833069, 0.06898334,
       0.1174705 , 0.19621645, 0.24779163, 0.18064038, 0.21892951,
       0.46153386, 0.08486003, 0.13182602, 0.17696687, 0.17397756,
       0.04892488, 0.17161035, 0.03559082, 0.05863097, 0.15064898,
       0.14819536, 0.09613513, 0.05372672, 0.36050753, 0.21457516,
       0.26253357, 0.12619605, 0.25537749, 0.10648643, 0.06925592,
       0.19913189, 0.16898361, 0.10082767, 0.1723249 , 0.14064761,
       0.09392476, 0.1191133 , 0.03416508, 0.10275136, 0.0834851 ,
       0.18127599, 0.0286131 , 0.11478253, 0.13137157, 0.050849  ,
       0.09538903, 0.29251024, 0.15839086, 0.12593056, 0.06807384,
       0.11957563, 0.0279194 , 0.0635707 , 0.11659092, 0.07133179,
       0.08097611, 0.26045092, 0.35515883, 0.11468734, 0.13838381,
       0.04436258, 0.08193275, 0.06731702, 0.24620429, 0.02177076,
       0.16960729, 0.05529374, 0.03093857, 0.25525431, 0.15257588,
       0.26789431, 0.0735437 , 0.10145521, 0.30310708, 0.06310551,
       0.3495877 , 0.11010943, 0.30714484, 0.03120479, 0.2294475 ,
       0.13579355, 0.0213488 , 0.26320315, 0.09498772, 0.08844785,
       0.13463748, 0.19167882, 0.08675437, 0.35724972, 0.24465506,
       0.24708882, 0.09797664, 0.05975305, 0.10900035, 0.32407791,
       0.28888161, 0.08296607, 0.09137482, 0.31051349, 0.30828688,
       0.11760564, 0.07320422, 0.13066405, 0.1061109 , 0.38213883,
       0.24671296, 0.09228173, 0.07184709, 0.07874081, 0.10364831,
       0.04975973, 0.038649  , 0.057948  , 0.35750919, 0.2170122 ,
       0.23662443, 0.13437277, 0.35687048, 0.03573748, 0.34306141,
       0.05000058, 0.14183865, 0.03309123, 0.08316827, 0.17671339,
       0.02181924, 0.35281425, 0.24851187, 0.27088442, 0.49122818,
       0.30088696, 0.03105669, 0.14420152, 0.44135849, 0.30196014,
       0.03567515, 0.14930657, 0.21000187, 0.06670402, 0.22769444,
       0.28084192, 0.06453634, 0.38328922, 0.1661532 , 0.02843402,
       0.17310544, 0.18558611, 0.09820305, 0.38593659, 0.12245045,
       0.19430582, 0.0465422 , 0.10527093, 0.06002692, 0.07172649,
       0.0965593 , 0.27485929, 0.10545837, 0.06815495, 0.16650028,
       0.12468095, 0.15497097, 0.04118411, 0.12185733, 0.12304727,
       0.54266995, 0.09466863, 0.1136917 , 0.11125018, 0.28915824,
       0.13685809, 0.02603663, 0.14897529, 0.08851778, 0.0479774 ,
       0.41890618, 0.0706187 , 0.10711539, 0.21092829, 0.21412819,
       0.05315317, 0.09333371, 0.19075639, 0.04434419, 0.04913914,
       0.1008944 , 0.03826115, 0.05935855, 0.10998082, 0.33715215,
       0.17918855, 0.04141891, 0.19285385, 0.11561836, 0.06513407,
       0.0254895 , 0.03179268, 0.27508875, 0.11894456, 0.06784893,
       0.30409795, 0.19786342, 0.30368729, 0.08513045, 0.08835135,
       0.15650154, 0.11879648, 0.18248147, 0.1574748 , 0.05430712,
       0.11890187, 0.07562167, 0.0722559 , 0.15681791, 0.06044325,
       0.227236  , 0.30334448, 0.05378846, 0.10592587, 0.46027831,
       0.41114569, 0.19728409, 0.13510645, 0.11255506, 0.28952875,
       0.13069313, 0.03735546, 0.19711364, 0.19684853, 0.26354652,
       0.17949279, 0.27109817, 0.07295483, 0.08946208, 0.33060124,
       0.11816077, 0.06853614, 0.21439494, 0.03689193, 0.05245648,
       0.35504005, 0.05350091, 0.03700831, 0.04780815, 0.06983732,
       0.19341913, 0.09040081, 0.28598744, 0.17821773, 0.10235415,
       0.19494185, 0.13186659])

In [12]:
y_pred_label = (y_pred >= 0.25).astype(int)
y_pred_label

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0])

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix

confusion_matrix(y_test, y_pred_label)

array([[515,  95],
       [ 86,  36]])

In [14]:
accuracy_score(y_test, y_pred_label)

0.7527322404371585

In [15]:
(515 + 36) / (515 + 95 + 86 + 36)

0.7527322404371585